### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by jayhesselberth** [rnabioco/2a-peptide-search#3]
- [ ] Examine distribution of protein domains on N- and C-terminal sides of 2A peptides
- [ ] Examine codon usage across 2A peptides. This is only straightforward (possible?) with Uniprot entries.
- [ ] Examine proteins that have more than one 2A peptide. Are there any that have examples of both class I and II? Of those that have multiple class I and class II, are there sequences the same / different?
- [ ] Compare phylogenies of class I and II. Quantify usage of e.g. class II in dsRNA viruses, Ixodes, dinoflagellates.

Do phage encode 2A peptides? May be a way to identify peptides that work in bacteria.

Devi mentioned that the extended peptides are more active, clarify with her
